import {
  html,
  css,
  js,
  typescript,
  react,
  figma,
  git,
  card1,
  card2,
  card3,
  card4,
  card5,
  card6,
  card0,
  card7,
  card8,
  card9,
  card10,
  card11,
  card12,
  card13,
} from "../assets";

export const navLinks = [
  {
    id: "home",
    title: "Home",
  },
  {
    id: "skills",
    title: "Skills",
  },
  {
    id: "portfolio",
    title: "Portfolio",
  },
  {
    id: "contactme",
    title: "Contact Me",
  },
];

export const mySkills = [
  {
    id: "html",
    title: "Html",
    icon: html,
  },
  {
    id: "css",
    title: "Css",
    icon: css,
  },
  {
    id: "javascript",
    title: "Javascript",
    icon: js,
  },
  {
    id: "typescript",
    title: "Typescript",
    icon: typescript,
  },
  {
    id: "react",
    title: "React",
    icon: react,
  },
  {
    id: "figma",
    title: "Figma",
    icon: figma,
  },
  {
    id: "git",
    title: "Git",
    icon: git,
  },
];

export const cards = [
  {
    id: "1",
    image: card1,
    cate: "frontend",
    title: "Game hub - RAWG API",
    dis: "HTML & Chakra ui & Ts & ReactJs",
    url: "https://hsn4.github.io/react-game-hub/",
    code: "https://github.com/HSN4/react-game-hub",
  },
  {
    id: "9",
    image: card9,
    cate: "UI/UX",
    title: "Esmani App",
    dis: "HTML & CSS & Js ",
    url: "https://www.behance.net/gallery/180100861/Esmani-app-(Case-Study)",
    code: "https://www.behance.net/7ussein7ussein",
  },
  {
    id: "0",
    image: card0,
    cate: "frontend",
    title: "Bank Modern App",
    dis: "HTML & Tailwind & Js & ReactJs",
    url: "https://hsn4.github.io/bank_modern_app/",
    code: "https://github.com/HSN4/bank_modern_app",
  },

  {
    id: "2",
    image: card2,
    cate: "frontend",

    title: "Popular movies - TMDb API",
    dis: "HTML & CSS & Js",
    url: "https://hsn4.github.io/moves-API/",
    code: "https://github.com/HSN4/moves-API",
  },
  {
    id: "11",
    image: card11,
    cate: "UI/UX",
    title: "Barmej App",
    dis: "Figma ",
    url: "https://www.behance.net/gallery/176861915/Online-Courses-App-Barmej",
    code: "https://github.com/HSN4/weekaway-react",
  },
  {
    id: "3",
    image: card3,
    cate: "frontend",

    title: "Responsive Web Design",
    dis: "HTML & CSS & Js",
    url: "https://hsn4.github.io/Responsive-Website/",
    code: "https://github.com/HSN4/Responsive-Website",
  },
  {
    id: "4",
    image: card4,
    cate: "frontend",

    title: "Javascript questions",
    dis: "HTML & CSS & Js & JSON",
    url: "https://hsn4.github.io/javascript-question/",
    code: "https://github.com/HSN4/javascript-question",
  },
  {
    id: "12",
    image: card12,
    cate: "UI/UX",
    title: "Anime Cloud",
    dis: "Figma",
    url: "https://www.behance.net/gallery/178598627/Mobile-App-Redesign",
    code: "https://www.behance.net/7ussein7ussein",
  },
  {
    id: "5",
    image: card5,
    cate: "frontend",

    title: "Responsive Web Design",
    dis: "HTML & CSS & Js ",
    url: "https://hsn4.github.io/My-First-Project/",
    code: "https://github.com/HSN4/My-First-Project",
  },
  {
    id: "6",
    image: card6,
    cate: "frontend",
    title: "Responsive Web Design",
    dis: "HTML & CSS & Js ",
    url: "https://hsn4.github.io/first-website-using-javascript/",
    code: "https://github.com/HSN4/first-website-using-javascript",
  },

  {
    id: "13",
    image: card13,
    cate: "UI/UX",
    title: "Sweets App",
    dis: "Figma",
    url: "https://www.behance.net/gallery/180177025/Sweets-App",
    code: "https://www.behance.net/7ussein7ussein",
  },
  {
    id: "10",
    image: card10,
    cate: "frontend",
    title: "Weekaway Website",
    dis: "HTML & Tailwind & reactjs ",
    url: "https://hsn4.github.io/weekaway-react/",
    code: "https://github.com/HSN4/weekaway-react",
  },
  {
    id: "7",
    image: card7,
    cate: "UI/UX",
    title: "Al-ittihad Store",
    dis: "Figma ",
    url: "https://www.behance.net/gallery/167996381/Al-ittihad-store",
    code: "https://www.behance.net/7ussein7ussein",
  },
  {
    id: "8",
    image: card8,
    cate: "UI/UX",
    title: "Saudi flag day",
    dis: "Figma ",
    url: "https://www.behance.net/gallery/171729063/Saudi-flag-day",
    code: "https://www.behance.net/7ussein7ussein",
  },
];
